{{- if and .Values.taigaGateway.ingress.enabled -}}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion   -}}
{{- if semverCompare ">=1.14-0" $kubeVersion -}}
{{- $fullName := include "taiga.fullname" . -}}
{{- if semverCompare ">=1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- with .Values.taigaGateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.taigaGateway.ingress.tls }}
  tls:
  {{- range .Values.taigaGateway.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.taigaGateway.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $kubeVersion }}
              service:
                name: {{ $fullName }}-gateway
                port:
                  name: http
              {{- else if semverCompare ">=1.14-0" $kubeVersion }}
              backend:
                serviceName: {{ $fullName }}-gateway
                servicePort: http
              {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
