name: Package changes so helm can access

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: lint chart
        run: helm lint .
                
      - uses: actions/checkout@v2
        with:
          repository: nemonik/helm-charts
          token: ${{ secrets.ACTION_TOKEN }}
          path: helm-charts
          ref: master
          
      - name: Package and push chart
        run: |
          PROJECT=$(basename ${GITHUB_WORKSPACE})
          PROJECT="${PROJECT/-helm/}"
          cd helm-charts
          git pull
          mkdir -p sources
          cd sources
          rsync -av --progress ${GITHUB_WORKSPACE}/. ${PROJECT} --exclude helm-charts --exclude .git --exclude *.tgz --exclude delete_taiga.sh --exclude example-values.yaml --exclude createsuperuser.sh --exclude manage.sh --exclude start_taiga.sh --exclude .github --exclude .gitignore --exclude robot.txt
          cd .. 
          helm package sources/*
          helm repo index --url https://nemonik.github.io/helm-charts/ .  
          git config user.name nemonik
          git config user.email github.com@nemonik.com 
          git add .
          git commit -m "generated"
          git push
          
